# Generated by Django 4.1.7 on 2023-02-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_rename_posts_post_profile_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cover_photo',
            field=models.ImageField(blank=True, upload_to='profile_cover_pictures'),
        ),
    ]
