# Generated by Django 4.1.7 on 2023-02-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_alter_profile_profile_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('post_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='post_pictures/')),
                ('default', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.post')),
            ],
        ),
    ]
