# Generated by Django 4.1.7 on 2023-02-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_remove_post_images_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='default',
        ),
    ]
