# Generated by Django 4.1.7 on 2023-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_remove_postimages_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='name',
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(upload_to='post_pictures'),
        ),
    ]
