# Generated by Django 4.1.7 on 2023-02-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
