# Generated by Django 4.1.7 on 2023-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
