# Generated by Django 4.1.7 on 2023-03-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0014_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anonymous',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
